version: '3'

services:
  axon:
    image: axoniq/axonserver
    hostname: axon
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
  jaeger:
    image: jaegertracing/all-in-one:1.7
    container_name: jaegertracing
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"